# Generated by Django 5.1.1 on 2024-09-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_table_comment_task_status_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='tasks/files/'),
        ),
        migrations.AddField(
            model_name='task',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/images/'),
        ),
    ]
